- name: Install and start Nginx on EC2
  hosts: all
  become: true
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Replace default Nginx index.html with hostname
      shell: "echo $(hostname) | sudo tee /usr/share/nginx/html/index.html > /dev/null"
